### ISSUE TITLE
Conditional disabled.

### ISSUE THREAD

**Issue by brezetsky** [fkhadra/react-contexify#17]
How to add conditional disabled?
I am trying like this disabled={conditional}. But this doesn't works. At least, disabled={true} makes item looks like disabled, onClick will work, but menu will not disappear.

**Comment by fkhadra** [comment]
When you click on a disabled item the menu will not disappear because this is the normal behavior. You can try to click on a disabled item with the native context menu, you will see that the menu will not disappear.

Regarding the conditional disabled, the best would be to use a ternary so you are sure that the condition will return true or false :
`
<Item disabled={condition ? true : false } />
`

Or you have to be sure that your condition will return true or false:
`
<Item disabled={condition === 1} />
`

I guess that you are using a condition like :
`
<Item disabled={condition && something} />
` 

In that case, if the condition is not true you will probably get `null` instead of `false`.

**Comment by brezetsky** [comment]
Please, close this issue. It was a problem with event bubbling, not with conditional, sorry.
For condition I propose next
<Item disabled={!!condition } />

**Comment by fkhadra** [comment]
Ok ok
