### ISSUE TITLE
Does not work/possible scam

### ISSUE THREAD

**Issue by hybridwebdev** [fkhadra/react-contexify#40]
Beware to all considering using this repo. Installation of this via NPM absolutely destroy my dependencies, forcing me to have to rebuild from a package. Luckily I create backups everytime i install new packages. 
Second attempt bore same results. Do not use this package if you read this. Nice try dev, i'm sure you got lots of people with this little scam. 
I do not give my consent for this to be locked/removed as I want others to see this as a warning.

**Comment by fkhadra** [comment]
Dear @hybridwebdev,

I don't know which issues you encountered. But your post is not contructive at all. Since you are on github, I can see that all the issues you opened are not constructive either.

Here is a working sample on codesanbox:
[![Edit ym758qx7vx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ym758qx7vx)

Peace
