### ISSUE TITLE
Left click to trigger the menu

### ISSUE THREAD

**Issue by charlot567** [fkhadra/react-contexify#84]
Hi,

Can you give us an example on how to trigger the context menu with a left click ? 

Thanks !

**Comment by fkhadra** [comment]
Hey @charlot567,

For the version 3

```js
<ContextMenuProvider event="onClick" {...otherProps}/>
``` 
I also published the v4-rc1 yesterday if you want to have a look. You can check the new documentation [here](https://fkhadra.github.io/react-contexify/). If the documentation site is not working properly it's probably due to the service worker.

You should see something like below
<img width="896" alt="screenshot 2018-10-25 at 13 15 34" src="https://user-images.githubusercontent.com/5574267/47496750-1a9cb780-d858-11e8-9f90-75d9b6220ef9.png">

**Comment by charlot567** [comment]
@fkhadra Thanks !
